### ISSUE TITLE
Request: Support for self-hosted Jira software servers.

### ISSUE THREAD

**Issue by ASAPHAANING** [web-pal/chronos-timetracker#34]

**Comment by VladimirPal** [comment]
Hi! Can you give us more details please?
We already have such functionality, you can connect to self-hosted jira.

**Comment by ASAPHAANING** [comment]
@VladimirPal Doesn't work. I tried giving it my URL, then prompt it with my username(my self hosted jira doesnt accept email like the chronos credentials placeholder field requires) but it never works. 

I'm on Linux x86-64.

**Comment by VladimirPal** [comment]
@ASAPHAANING We don't have any constraints for self-hosted server, can you check last version please?
https://chronos-api.web-pal.com/release/AppImage

**Comment by ASAPHAANING** [comment]
Tried this new version on two different computers, still can't log in. When I go back to step 1 (URL) I notice that an SSL enabled HTTP URL has been added although I typed the regular HTTP. Could this be the cause of the error?

**Comment by Architektor** [comment]
@ASAPHAANING what if you remove "s" from https and try to login? It still replaces http with https even if you remove the "s" manually?

**Comment by VladimirPal** [comment]
@ASAPHAANING It could be cause of the error, but we can't reproduce it, it's strange.

**Comment by VladimirPal** [comment]
@ASAPHAANING We just released 2.4.3, could you check please?

**Comment by ASAPHAANING** [comment]
Tried 2.4.3, thanks. That certainly fixed the https -> http error but I am still unable to log in. It still prompts for an email although my jira only accepts username logins, maybe there's something there?

**Comment by VladimirPal** [comment]
Despite the fact that input placeholder "Enter email" you can enter any data, we don't have email validation.
We have a working users with self-hosted jira.
Can you figure out your Jira server version?

**Comment by ASAPHAANING** [comment]
That's what I thought. Doesn't work with my username though. The jira server version:

v7.0.9#70119

**Comment by VladimirPal** [comment]
We found the bug and fixed it in 2.4.4 version, but working with jira-client without https may cause some issues, check it please.

**Comment by ASAPHAANING** [comment]
Will do @VladimirPal, now it's confirmed working on my end! ;) I did have to manually add "http://" to my url though, just a UX note.

**Comment by VladimirPal** [comment]
@ASAPHAANING It would be great if you type two words on marketplace reviews - https://marketplace.atlassian.com/plugins/com.web-pal.jira.plugins.chronos/cloud/reviews
something like ```good``` or ```bad``` will be enought, also github star :star: will help us too. Thank you. :pray: :metal:
